- name: Clone dotfile repos
  git:
    repo: 'https://github.com/jcrd/{{ item.repo }}'
    dest: '{{ configdir }}/{{ item.dest }}'
    update: no
  loop:
    - { repo: 'configs', dest: 'configs' }
    - { repo: 'zsh-config', dest: 'zsh' }

- name: Configure dotfiles
  shell: >
    cd {{ configdir }}/{{ item }} &&
    source ../zsh/zshenv &&
    ./configure
  loop:
    - configs
    - zsh
