- name: Check existence of container
  command: podman container exists thelounge
  register: container_exists
  failed_when: container_exists.rc > 1

- name: Create container
  shell: >
    podman create --name=thelounge \
    -p 9000:9000 \
    -v thelounge:/var/opt/thelounge \
    thelounge/thelounge
  when: container_exists.rc == 1

- name: Configure firewalld
  firewalld:
    port: '{{ item }}'
    state: enabled
    immediate: yes
    permanent: yes
  loop:
    - 9000/tcp
  become: yes
  when: container_exists.rc == 1

- name: Install systemd service
  copy:
    src: thelounge.service
    dest: '{{ configdir }}/systemd/user/thelounge.service'

- name: Enable systemd service
  systemd:
    name: thelounge.service
    scope: user
    state: started
    enabled: yes
