- name: Install epel repo
  dnf: name=epel-release
  become: true

- name: Install base packages
  dnf:
    name:
      - git
      - lm_sensors
      - mosh
      - neovim
      - podman
      - psmisc
      - tmux
      - zsh
  become: true

- name: Configure firewalld for mosh
  firewalld:
    port: 60000-61000/udp
    state: enabled
    immediate: true
    permanent: true
  become: true

- name: Enable cockpit socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: true
  become: true

- name: Set zsh as user shell
  user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/zsh
  become: true

- name: Enable loginctl linger
  command: loginctl enable-linger {{ ansible_user_id }}

- name: Enable sshd pubkey authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PubkeyAuthentication true'
  become: true

- name: Create ssh directory with correct permissions
  file:
    path: '{{ homedir }}/.ssh'
    state: directory
    mode: 0700
