- name: Install epel repo
  dnf: name=epel-release
  become: yes

- name: Install base packages
  dnf:
    name:
      - git
      - lm_sensors
      - neovim
      - openvpn
      - podman
      - psmisc
      - tmux
      - zsh
  become: yes

- name: Enable cockpit socket
  systemd:
    name: cockpit.socket
    enabled: yes
  become: yes

- name: Set zsh as user shell
  user:
    name: '{{ ansible_user }}'
    shell: /usr/bin/zsh

- name: Enable loginctl linger
  command: loginctl enable-linger {{ ansible_user }}
