- name: Enable copr repos
  command: dnf copr -y enable {{ item }}
  args:
    warn: false
  loop:
    - jcrd/hdparmify
  become: true

- name: Install base packages
  dnf:
    name:
      - git
      - hdparmify
      - htop
      - kitty-terminfo
      - lm_sensors
      - mosh
      - neovim
      - podman
      - progress
      - psmisc
      - ranger
      - tmux
      - zsh
  become: true

- name: Configure firewalld for mosh
  firewalld:
    port: 60000-61000/udp
    state: enabled
    immediate: true
    permanent: true
  become: true

- name: Set zsh as user shell
  user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/zsh
  become: true

- name: Enable loginctl linger
  command: loginctl enable-linger {{ ansible_user_id }}

- name: Enable sshd pubkey authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    line: 'PubkeyAuthentication yes'
  become: true

- name: Create ssh directory with correct permissions
  file:
    path: '{{ homedir }}/.ssh'
    state: directory
    mode: 0700
