- name: Install epel repo
  dnf: name=epel-release
  become: yes

- name: Install base packages
  dnf:
    name:
      - git
      - lm_sensors
      - mosh
      - neovim
      - podman
      - psmisc
      - tmux
      - zsh
  become: yes

- name: Configure firewalld for mosh
  firewalld:
    port: 60000-61000/udp
    state: enabled
    immediate: yes
    permanent: yes
  become: yes

- name: Enable cockpit socket
  systemd:
    name: cockpit.socket
    state: started
    enabled: yes
  become: yes

- name: Set zsh as user shell
  user:
    name: '{{ ansible_user_id }}'
    shell: /usr/bin/zsh
  become: yes

- name: Enable loginctl linger
  command: loginctl enable-linger {{ ansible_user_id }}
